name: study_planner
description: Plan your studies for your next exam.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^6.0.0
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  form_bloc: ^0.19.0
  flutter_form_bloc: ^0.19.0
  intl: ^0.16.1
  json_annotation: ^3.0.1
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  path_provider: ^1.6.11
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  build_runner: ^1.10.0
  json_serializable:  ^3.3.0
  hive_generator: ^0.7.1
  uuid: ^2.2.0
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/launcher-icon.png"

flutter_native_splash:
  image: assets/icon/app-icon.png
  color: "#fe3521"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#  assets:
#    - assets/icon/icon.png

  fonts:
    - family:  StudyPlanner
      fonts:
        - asset: fonts/app-icon.ttf